---
name: tntw

services:
  db:
    image: elasticsearch:8.15.3
    restart: always
    healthcheck:
      test: [
        "CMD-SHELL",
        "curl --silent --fail localhost:9200/_cluster/health || exit 1"
      ]
      timeout: 20s
      retries: 10
    environment:
      xpack.security.enabled: false  # I'm not doing a secure install
      discovery.type: single-node
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
  api:
    depends_on:
      db:
        condition: service_healthy
        restart: true
    image: tntw-api
    build:
      context: .
      target: development
    restart: always
    environment:
      TNTW_DATABASE_URL: ${TNT_DATABASE_URL:-http://db:9200}
    volumes:
      - type: bind
        source: src/
        target: /app
    ports:
      - 8000:8000
